In [1]:
import pandas as pd

ns_invoices = pd.read_excel("C:/Users/91934/Desktop/work/mecsotxn2Results894.xlsx")

sh = pd.read_csv("C:/Users/91934/Desktop/work/Try.csv")

ns_invoices.columns


sh_data = {'orderid' : sh['Order number'], 'Amount' : sh['Original price of the item']+ sh['Discounts on goods'] + sh['Seller coupon amount']}
ns_data = { 'orderid' : ns_invoices['PO/Check Number'], 'Amount' : ns_invoices['Converted Amount']}

sh_amount = pd.DataFrame(sh_data)
ns_amount = pd.DataFrame(ns_data)

merged = pd.merge(sh_amount,ns_amount, on='orderid', suffixes=('_sh', '_ns'))
filtered = merged[merged['Amount_ns'] != merged['Amount_sh']]


missing = sh_amount[sh_amount['orderid'].isin(ns_amount['orderid'])]['orderid']

promotion_data = {'orderid' : sh_amount['orderid'], "Shopee Promotion" : 'Shopee Promotion', "1" : "1" , 'rate' : sh['Seller coupon amount'] + sh['Shopee coin rebates provided by sellers']}
shipping_data = {'orderid' : sh_amount['orderid'], "Shopee Shipping" : 'Shopee Shipping', "1":"1" , 'rate': sh['Shopee coin rebates provided by sellers.1'] + sh['Shopee shipping subsidy'] + sh['The seller pays for the shipping costs']}

comission_data = {'orderid' :  sh_amount['orderid'], "Shopee Comission" : 'Shopee Comission',"1":"1", 'rate': sh['commission'] }
service_data = {'orderid' :  sh_amount['orderid'], "Shopee Service Fee" : 'Shopee Service Fee', "1":"1", 'rate': sh['service charge'] }
Transaction_data ={'orderid' :  sh_amount['orderid'], "Shopee Transaction Fee" : 'Shopee Transaction Fee', "1":"1", 'rate': sh['Transaction fees']}


promodata = pd.DataFrame(promotion_data)
shipping = pd.DataFrame(shipping_data)
comission = pd.DataFrame(comission_data)
service = pd.DataFrame(service_data)
transaction = pd.DataFrame(Transaction_data)

feeimport = pd.concat([promodata, shipping, comission, service, transaction])

feeimport








# check = df['PO/Check Number']
# filetered = df[df['Type'] == 'Invoice']
# filetered

,orderid,Shopee Promotion,1,rate,Shopee Shipping,Shopee Comission,Shopee Service Fee,Shopee Transaction Fee
0,231205CW98FVWQ,Shopee Promotion,1,-200.0,NaN,NaN,NaN,NaN
1,231125GRW68DP6,Shopee Promotion,1,0.0,NaN,NaN,NaN,NaN
2,231212214PQX5J,Shopee Promotion,1,-100.0,NaN,NaN,NaN,NaN
3,2312122QHDMM7J,Shopee Promotion,1,-150.0,NaN,NaN,NaN,NaN
4,2312132U2TBRXN,Shopee Promotion,1,-200.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
39,23121224XSXHXY,NaN,1,-48.0,NaN,NaN,NaN,Shopee Transaction Fee
40,231208MY5UCNBC,NaN,1,-47.0,NaN,NaN,NaN,Shopee Transaction Fee
41,231208N84JNJ79,NaN,1,-47.0,NaN,NaN,NaN,Shopee Transaction Fee
42,23121352RUDH9W,NaN,1,-36.0,NaN,NaN,NaN,Shopee Transaction Fee
43,2312011QXYAX0N,NaN,1,-62.0,NaN,NaN,NaN,Shopee Transaction Fee

In [25]:
ns_invoices.columns

Index(['Date', 'Name', 'PO/Check Number', 'Internal ID', 'Item', 'Quantity',
       'Item Rate', 'Amount', 'Brand', 'Status', 'Converted Itemrate',
       'Converted Amount', 'Location', 'Type', 'MARKETPLACE SETTLEMENT ID',
       'Channel', 'Account', 'Transaction Type', 'Document Number',
       'Created From'],
      dtype='object')